#!/bin/bash
#SBATCH -p long    # which partition to run on ('compute' is default)
#SBATCH -t 7-00:00:00    # maximum execution time: in this case one day, two hours and thirty minutes (optional)
#SBATCH --cpus-per-task=4
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --mem=300000
#SBATCH --mail-type FAIL 
#SBATCH --mail-user minhkhoi.pham@adaptcentre.ie 
#SBATCH -o %h/slurm_reports/slurm.%x.%j.out # STDOUT

# find open port  
PORT=$(python3 -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()')
scontrol update JobId="$SLURM_JOB_ID" Comment="$PORT"

echo "Starting sshd on port $PORT"  
/usr/sbin/sshd -D -p $PORT -f /dev/null -h "${HOME}/.ssh/id_ed25519"

