#!/bin/bash
#SBATCH -J vscode    # arbitrary name for the job (you choose)
#SBATCH -p compute    # which partition to run on ('compute' is default)
#SBATCH -t 2-00:00:00    # maximum execution time: in this case one day, two hours and thirty minutes (optional)
#SBATCH --cpus-per-task=2
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --mem=30000
#SBATCH --mail-type FAIL 
#SBATCH --mail-user minhkhoi.pham@adaptcentre.ie 
#SBATCH -o %h/slurm_reports/slurm.%x.%j.out # STDOUT
#SBATCH -w g108

/usr/sbin/sshd -D -p 2223 -f /dev/null -h ${HOME}/.ssh/id_ed25519
# find open port  
# PORT=$(python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()')  
# scontrol update JobId="$SLURM_JOB_ID" Comment="$PORT"

# # start sshd server on the available port  
# echo "Starting sshd on port $PORT"  
# /usr/sbin/sshd -D -p ${PORT} -f /dev/null -h ${HOME}/.ssh/id_rsa
